apple/swift-distributed-actors

Package.swift

=build update swift syntax dependency a little bit

---

README.md

Follow up based on https://forums.swift.org/t/are-there-notes-or-docs-on-how-to-use-a-nightly-development-snapshot-with-projects-swift-distributed-actors/53170/10
Thanks @slashmo for the info on CLion, I can confirm it works great!

Update readme with more info on build setup

---

Sources/DistributedActors/ActorSystem.swift
Sources/DistributedActors/_ActorShell.swift

Use ManagedAtomicLazyReference in ActorSystem for better race condition handling, see #855

WIP: Use ManagedAtomicLazyReference in ActorSystem

---

Sources/DistributedActors/Cluster/ClusterControl.swift
Sources/DistributedActors/Cluster/Reception/OperationLogDistributedReceptionist.swift

This fixes various documentation comments

Fix documentation comments typos

---

docker/docker-compose.2004.54.yaml
docker/docker-compose.2004.56.yaml

* add docker setup for 5.6
* update 5.4 to use release version

0.x CI setup

---

Sources/DistributedActors/ActorRef+Ask.swift
Sources/DistributedActors/ClusterSystem.swift
Sources/DistributedActors/InvocationBehavior.swift
Sources/DistributedActors/LifecycleMonitoring/LifecycleWatch.swift
Sources/DistributedActors/Serialization/Serialization+Manifest.swift
Sources/DistributedActors/Serialization/Serialization+Serializers+Protobuf.swift
Sources/DistributedActors/Serialization/Serialization+Settings.swift
Sources/DistributedActors/Serialization/Serialization.swift
Sources/DistributedActors/Serialization/TopLevelProtobufSerializer.swift
Sources/DistributedActors/_Mailbox.swift
Tests/DistributedActorsDocumentationTests/SerializationDocExamples.swift
Tests/DistributedActorsTests/DistributedReceptionistTests.swift
Tests/DistributedActorsTests/SerializationTests.swift

Resolves https://github.com/apple/swift-distributed-actors/issues/883

Serialization cleanup

---

Sources/DistributedActors/ClusterSystem.swift
Sources/DistributedActors/ClusterSystemSettings.swift
Sources/DistributedActorsTestKit/ShouldMatchers.swift
Tests/DistributedActorsTests/ClusterSystemTests.swift

Resolves https://github.com/apple/swift-distributed-actors/issues/881

Make remote call timeout configurable

---

Sources/DistributedActors/ActorContext.swift
Sources/DistributedActors/ActorRef+Ask.swift
Sources/DistributedActors/AsyncResult.swift
Sources/DistributedActors/Pattern/WorkerPool.swift
Sources/DistributedActors/Receptionist/ReceptionistOperations.swift
Sources/DistributedActors/Receptionist/SystemReceptionist.swift
Tests/DistributedActorsTests/ActorAskTests.swift

Make _AsyncResult and APIs using it internal

---

Sources/DistributedActors/ActorRefFactory.swift
Sources/DistributedActors/ClusterSystem.swift
Sources/DistributedActors/Receptionist/ActorContext+Receptionist.swift
Sources/DistributedActors/Receptionist/Receptionist.swift
Sources/DistributedActors/Receptionist/ReceptionistOperations.swift
Sources/DistributedActors/Receptionist/SystemReceptionist.swift

Part 1 of https://github.com/apple/swift-distributed-actors/issues/890

Hide SystemReceptionist

---

Sources/ActorSingletonPlugin/ActorSingletonProxy.swift
Sources/DistributedActors/Behaviors.swift
Sources/DistributedActors/Cluster/ClusterEventStream.swift
Sources/DistributedActors/Cluster/ClusterShell.swift
Sources/DistributedActors/Cluster/DiscoveryShell.swift
Sources/DistributedActors/Cluster/Reception/_OperationLogClusterReceptionistBehavior.swift
Sources/DistributedActors/EventStream.swift
Sources/DistributedActors/Gossip/Gossiper+Shell.swift
Sources/DistributedActors/InvocationBehavior.swift
Sources/DistributedActors/LifecycleMonitoring/LifecycleWatch.swift
Sources/DistributedActors/LifecycleMonitoring/_BehaviorDeathWatch.swift
Sources/DistributedActors/Pattern/WorkerPool.swift
Sources/DistributedActors/Supervision.swift
Sources/DistributedActors/SystemMessages.swift
Sources/DistributedActors/_ActorShell.swift
Sources/DistributedActors/_Signals.swift
Sources/DistributedActorsTestKit/TestProbes.swift
Tests/DistributedActorsTests/BehaviorCanonicalizeTests.swift
Tests/DistributedActorsTests/BehaviorTests.swift
Tests/DistributedActorsTests/InterceptorTests.swift
Tests/DistributedActorsTests/NodeDeathWatcherTests.swift
Tests/DistributedActorsTests/ParentChildActorTests.swift
Tests/DistributedActorsTests/SerializationTests.swift
Tests/DistributedActorsTests/SupervisionTests.swift
Tests/DistributedActorsTests/_DeathWatchTests.swift

Hide signals, we'll remove them eventually along with behaviors.
Terminated signal has been replaced with just method calls :)

[hide] Hide more types to be removed: Signal, Signals

---

Sources/DistributedActors/ClusterSystem.swift
Sources/DistributedActors/Refs.swift
Tests/DistributedActorsTests/ClusterSystemTests.swift

Resolves https://github.com/apple/swift-distributed-actors/issues/887

Carry back remote call error

---

Sources/DistributedActors/Cluster/ClusterShell.swift
Sources/DistributedActors/Cluster/Downing/DowningStrategy.swift
Sources/DistributedActors/Cluster/Downing/TimeoutBasedDowningStrategy.swift
Sources/DistributedActors/ClusterSystem.swift

Resolves https://github.com/apple/swift-distributed-actors/issues/935

Convert DowningStrategyShell into a distributed actor

---

Sources/ActorSingletonPlugin/ActorSingletonPlugin.swift
Sources/DistributedActors/ClusterSystem.swift
Sources/DistributedActors/Plugins/ActorSystem+Plugins.swift
Sources/DistributedActors/Plugins/ActorSystemSettings+Plugins.swift

Pave way for https://github.com/apple/swift-distributed-actors/issues/824

Make plugin API async

---

Sources/DistributedActors/ClusterSystem.swift
Sources/DistributedActors/LifecycleMonitoring/LifecycleWatch.swift
Tests/DistributedActorsTests/LifecycleWatchTests.swift

Resolves https://github.com/apple/swift-distributed-actors/issues/930

watchTermination should support async 'whenTerminated'

---

Package.swift

To latest    ` .package(url: "https://github.com/apple/swift-nio.git", from: "2.40.0"),`

Update NIO requirement

---

Sources/DistributedActors/Cluster/Reception/OperationLogDistributedReceptionist.swift
Tests/DistributedActorsTests/Pattern/WorkerPoolTests.swift

Resolves https://github.com/apple/swift-distributed-actors/issues/919

Receptionist should flush registrations in order by version

---

Tests/DistributedActorsTests/DistributedReceptionistTests.swift

The fix for https://github.com/apple/swift-distributed-actors/issues/919 seems to fix these tests too.
Resolves https://github.com/apple/swift-distributed-actors/issues/953

Update receptionist tests

---

docker/docker-compose.2004.57.yaml

Bad docker image name used in docker-compose for 5.7

=docker Fix 5.7 docker image name

---

IntegrationTests/tests_01_cluster/it_Clustered_swim_suspension_reachability/main.swift
Sources/DistributedActors/Cluster/ClusterEventStream.swift
Sources/DistributedActors/Cluster/Leadership.swift
Sources/DistributedActors/Cluster/NodeDeathWatcher.swift
Sources/DistributedActors/Cluster/Reception/_OperationLogClusterReceptionistBehavior.swift
Sources/DistributedActors/Gossip/Gossiper+Shell.swift
Sources/DistributedActorsTestKit/ActorTestKit.swift
Tests/DistributedActorsTests/Cluster/AssociationClusteredTests.swift
Tests/DistributedActorsTests/Cluster/ClusterEventStreamTests.swift
Tests/DistributedActorsTests/Cluster/ClusterLeaderActionsClusteredTests.swift

Follow up for https://github.com/apple/swift-distributed-actors/pull/1012

Address remaining feedback in #1012

---

Sources/DistributedActors/ActorMessages.swift
Sources/DistributedActors/Cluster/Cluster+Member.swift
Sources/DistributedActors/Cluster/Cluster+Membership.swift
Sources/DistributedActors/Cluster/ClusterControl.swift
Sources/DistributedActors/Cluster/ClusterShell.swift
Sources/DistributedActors/Cluster/Leadership.swift
Sources/DistributedActors/Cluster/Protobuf/ClusterEvents+Serialization.swift
Sources/DistributedActors/Cluster/Protobuf/Membership+Serialization.swift
Sources/DistributedActors/Metrics/Metrics+ClusterSystem.swift
Sources/DistributedActorsTestKit/Cluster/ClusteredActorSystemsXCTestCase.swift
Tests/DistributedActorsTests/ActorLeakingTests.swift
Tests/DistributedActorsTests/MembershipTests.swift
Tests/DistributedActorsTests/_DeathWatchTests.swift

Part of https://github.com/apple/swift-distributed-actors/issues/999

Make public enums into structs or hide them (part 2)

---

Sources/DistributedActors/Cluster/Reception/OperationLogDistributedReceptionist.swift
Sources/DistributedActors/Receptionist/DistributedReception.swift
Sources/DistributedActors/Receptionist/DistributedReceptionist.swift
Sources/DistributedActors/utils.swift
Tests/DistributedActorsTests/DistributedReceptionistTests.swift

Resolves https://github.com/apple/swift-distributed-actors/issues/1048

=reception immediately flush already known regs to a listing

---

scripts/docs/generate_docc.sh

- Project README indicates docs can be generated, however when attempting to do so, an error occurs 
- Following @ktoso suggestion
- Use full command rather than alias
- Resolves #1162 
- Will now have the ability to generate docs

ISSUE-1162: Unable To Generate Docs
