apple/swift-distributed-actors

- Sources/DistributedActors/ActorSystem.swift
This is the continuation of what was done in #857 (see also #855) : `ManagedAtomicLazyReference` is used to protect the `_cluster: ClusterShell` property as well against memory level race conditions.
> Store ClusterShell using a ManagedAtomicLazyReference

- README.md
- scripts/docs/generate_docc.sh
- scripts/docs/preview_docc.sh
- Remove docc and docc render build
- Update README.md to reflect docc change
#856
#863 
Update scripts/docs/generate_docc.sh and scripts/docs/preview_docc.sh
Update the README description about docc and update the recommend swift-nightly-toolchain to 2021-11-02
> Since the docc and docc-render ship with the toolchain from that tag https://github.com/apple/swift/pull/39723
- Resolves #856
> Update the usage of docc

- IntegrationTests/tests_04_cluster/it_Clustered_swim_ungraceful_shutdown/main.swift
- IntegrationTests/tests_04_cluster/test_02_ungraceful_shutdown_recovery.sh
- Package.swift
- Sources/DistributedActors/Cluster/Cluster+Membership.swift
- Sources/DistributedActors/Cluster/ClusterShellState.swift
- Tests/DistributedActorsTests/MembershipTests.swift
Make sure a previous cluster member is marked as `.down` before replacing it
* Resolve #866 
* When processing a `MemberChange` that replaces an existing node, mark the node as `.down` if it hasn't been already
* Add an integration test for #866 (confirmed failure before this change.
- Resolves #866
> Down replaced cluster members

- Package.swift
Add support for Swift 5.6 to Package.swift, namely pull in a stable SwiftSyntax version.
This is only for the legacy release/0.x version.
> Add Swift 5.6 support.

- Package.swift
- Sources/GenActorsLib/GenerateActors.swift
- Tests/GenActorsTests/ClassStructEtcActorable/ClassStructEtc+Actorable.swift
Adapt codebase for Swift 5.6 release version
I wanted to try out Distributed Actors library on my Mac having Swift 5.6 release installed but it could not even compile. So I decided to fix the code base. 
I applied the following fixes to the codebase,
- Fixed and updated SwiftSyntax dependency in Package.swift
- Fixed SwiftSyntax import in GenActions Swift source
- Made a test class final to meet a requirement imposed by Actorable protocol.
The whole codebase now compiles with Swift 5.6. Also the full test suite is passed. All the changes made on a MacBook Pro mid 2015 running the latest macOS (Monterey 12.3.1) and Xcode 13.3.
> Adapt codebase for Swift 5.6 release version

- Sources/DistributedActors/Cluster/Reception/OperationLogDistributedReceptionist.swift
- Sources/DistributedActors/ClusterSystem.swift
- Sources/DistributedActors/InvocationBehavior.swift
- Sources/DistributedActors/LifecycleMonitoring/LifecycleWatch.swift
- Sources/DistributedActors/Serialization/Serialization+Context.swift
- Sources/DistributedActors/Serialization/Serialization+Invocation.swift
- Sources/DistributedActors/Serialization/Serialization.swift
- Tests/DistributedActorsTests/Cluster/Reception/OpLogDistributedReceptionistClusteredTests.swift
- Tests/DistributedActorsTests/DistributedReceptionistTests.swift
Some tests were failing with `error=missingSerializationContext(DistributedActors.VersionVector, details: "DistributedActors.Serialization.Context not available in Foundation.(unknown context at $18e133fb8).__JSONEncoder.userInfo, but is necessary encode message: [[actor:/system/receptionist: 1]]:DistributedActors.VersionVector"` since invocation encoder/decoder did not properly use the `Serialization` infra.
Fixing this silly omission, fixes all those tests.
I'll do some more cleanup there in a bit but first want a green CI back.
> [ser] Invocation serialization should use the Serialization infra

- Package.swift
- Samples/Package.swift
- Samples/Sources/SampleDiningPhilosophers/DistributedDiningPhilosophers.swift
- Sources/DistributedActors/Cluster/ClusterShell.swift
- Sources/DistributedActors/Cluster/Reception/OperationLogDistributedReceptionist.swift
- Tests/DistributedActorsTests/ActorRefAdapterTests.swift
- scripts/integration_tests.sh
This test is a bit weird in the new world -- it does not make sense in the local only world, because if we have a reference to an actor it IS alive, so we'll never deadletter here.
The same can be reproduced cross node, but we test that in other ways I believe.
> [test] remove dead letter test which is hard to reproduce in Swift DA

- Package.swift
- Samples/Package.swift
- Samples/Sources/SampleDiningPhilosophers/DiningPhilosophers.swift
- Samples/Sources/SampleDiningPhilosophers/DistributedDiningPhilosophers.swift
- Samples/Sources/SampleDiningPhilosophers/Fork.swift
- Samples/Sources/SampleDiningPhilosophers/Philosopher.swift
- Samples/Sources/SampleDiningPhilosophers/SamplePrettyLogHandler.swift
- Samples/Sources/SampleDiningPhilosophers/boot.swift
- Samples/Tests/NoopTests/SampleTest.swift
- Sources/DistributedActors/Cluster/ClusterShell.swift
- Sources/DistributedActors/Cluster/Reception/OperationLogDistributedReceptionist.swift
- Sources/DistributedActors/ClusterSystem.swift
- Sources/DistributedActors/DistributedActor+Messages.swift
- Sources/ExecApp/boot.swift
- Tests/DistributedActorsTests/ActorLeakingTests.swift
- Tests/DistributedActorsTests/Cluster/RemoteActorRefProviderTests.swift
Resolves https://github.com/apple/swift-distributed-actors/issues/840
This does lock during init, and we can clean it up more nicely, but the locks are rarely hit and we only need them during initialization of the system actors. It is FINE if they're blocked for those few millis as the system actors initialize.
We'd have to do better to run the cluster on a single thread, but we'll do that if we ever need to.
> Resolve racy initialization where system actors need to reach for .cluster

- Sources/DistributedActors/Cluster/Association.swift
- Sources/DistributedActors/Cluster/ClusterShell.swift
- Sources/DistributedActors/ClusterSystem.swift
- Sources/DistributedActors/ClusterSystemSettings.swift
- Tests/DistributedActorsTests/ClusterSystemTests.swift
> Periodically prune association tombstones

- Sources/DistributedActors/Props.swift
- Sources/DistributedActors/Supervision.swift
- Sources/DistributedActorsConcurrencyHelpers/lock.swift
`can easily changed in-line` -> `can be easily changed in-line`
`an theater` -> `a theater`
`an supervisor` -> `a supervisor`
`Whenver` -> `Whenever`
> Fix typos in doc comments

- Sources/DistributedActors/ClusterSystem.swift
https://github.com/apple/swift-distributed-actors/issues/885
We had some bugs about actor ready being called many times by the compiler, and this should have been fixed by now
> Readying actors should not be arbitrarily called many times

- Sources/DistributedActorsTestKit/LogCapture.swift
Less warnings in code
We can use this method to just wait for a log to appear, without inspecting it.
> [testkit] awaitLogContaining is useful also without inspecting result

- Sources/DistributedActors/ActorRef+Ask.swift
- Sources/DistributedActors/Cluster/Reception/OperationLogDistributedReceptionist.swift
- Sources/DistributedActors/ClusterSystem.swift
- Tests/DistributedActorsTests/ActorAskTests.swift
- Tests/DistributedActorsTests/ClusterSystemTests.swift
Resolves https://github.com/apple/swift-distributed-actors/issues/905
> Rename AskError to RemoteCallError

- Sources/DistributedActors/ClusterSystem.swift
Resolves  #922
The newly added repeated task that does tombstone flushing was cancelled AFTER the ELG shutdown, leading to the  `ERROR: Cannot schedule tasks on an EventLoop that has already shut down. This will be upgraded to a forced crash in future SwiftNIO versions.` error explained in Don't schedule futures on terminated EventLoop #922.
We must not touch ELG related APIs after shutting down; A cancel seems to create a future as well, so it was causing issues.
FYI @drexin
> Must not touch EL based APIs after shutting down the ELG

- Sources/ActorSingletonPlugin/ActorSingletonProxy.swift
- Sources/DistributedActors/ActorRefProvider.swift
- Sources/DistributedActors/ClusterSystem.swift
- Sources/DistributedActors/ClusterSystemSettings.swift
- Sources/DistributedActorsTestKit/ActorSystemXCTestCase.swift
- Sources/DistributedActorsTestKit/Cluster/ClusteredActorSystemsXCTestCase.swift
- Tests/ActorSingletonPluginTests/ActorSingletonPluginTests.swift
- Tests/DistributedActorsTests/ActorRefAdapterTests.swift
- Tests/DistributedActorsTests/Cluster/MembershipGossipLogicSimulationTests.swift
- Tests/DistributedActorsTests/Cluster/RemoteActorRefProviderTests.swift
- Tests/DistributedActorsTests/ClusterSystemTests.swift
- Tests/DistributedActorsTests/SerializationTests.swift
- Tests/DistributedActorsTests/TraversalTests.swift
Partially revert https://github.com/apple/swift-distributed-actors/pull/902 but with `enabled` set to `true` by default instead of `false`.
> Bring back ClusterSystemSettings.enabled

- Sources/DistributedActors/ActorAddress.swift
- Sources/DistributedActors/Cluster/Cluster+Member.swift
- Sources/DistributedActors/Cluster/Cluster+Membership.swift
- Sources/DistributedActors/Cluster/ClusterControl.swift
- Sources/DistributedActors/Cluster/Reception/OperationLogDistributedReceptionist.swift
- Sources/DistributedActors/DistributedActors.docc/Clustering.md
- Sources/DistributedActors/Pattern/WorkerPool.swift
- Sources/DistributedActors/Receptionist/DistributedReceptionist.swift
- Tests/DistributedActorsTests/Cluster/Reception/OpLogDistributedReceptionistClusteredTests.swift
- Tests/DistributedActorsTests/DistributedReceptionistTests.swift
- Tests/DistributedActorsTests/Pattern/WorkerPoolTests.swift
Resolves https://github.com/apple/swift-distributed-actors/issues/927 for the first beta release.
We'll be adding much more docs, but this is a good enough first cut.
> Another chunk of documentation for beta-1

- Sources/DistributedActors/Cluster/Association.swift
- Sources/DistributedActors/Cluster/Transport/RemoteClusterActorPersonality.swift
- Sources/DistributedActors/Cluster/Transport/TransportPipelines.swift
- Sources/DistributedActors/ClusterSystem.swift
- Sources/DistributedActors/InvocationBehavior.swift
- Sources/DistributedActors/Refs.swift
- Tests/DistributedActorsTests/ClusterSystemTests.swift
Resolves https://github.com/apple/swift-distributed-actors/issues/947
> Implement remoteCall without ask actors

- Package.swift
- Sources/DistributedActors/ActorTags.swift
- Sources/DistributedActors/Behaviors.swift
- Sources/DistributedActors/StashBuffer.swift
- Sources/DistributedActors/Supervision.swift
- Sources/DistributedActors/_ActorShell.swift
- Sources/DistributedActors/_BehaviorTimers.swift
Before Swift / Xcode was released, we could not have the right availability markers and needed this flag.
Actually, the availability might still be wrong in nightly builds so I need to investigate a workaround...
> Remove -disable-availability-checking, Swift 5.7 is part of Xcode 14.0 and has right availabilities now

- Samples/Sources/SampleDiningPhilosophers/DistributedDiningPhilosophers.swift
- Sources/DistributedActors/Cluster/ClusterControl.swift
- Sources/DistributedActors/ClusterSystem.swift
- Sources/DistributedActorsTestKit/ActorTestKit.swift
- Sources/DistributedActorsTestKit/Cluster/ClusteredActorSystemsXCTestCase.swift
- Tests/DistributedActorsTests/Cluster/AssociationClusteredTests.swift
- Tests/DistributedActorsTests/Cluster/ClusterLeaderActionsClusteredTests.swift
- Tests/DistributedActorsTests/Cluster/ClusterMembershipSnapshotTests.swift
- Tests/DistributedActorsTests/Cluster/ClusterOnDownActionTests.swift
- Tests/DistributedActorsTests/Cluster/DowningStrategy/DowningClusteredTests.swift
- Tests/DistributedActorsTests/Cluster/MembershipGossipClusteredTests.swift
- Tests/DistributedActorsTests/Cluster/Reception/OpLogDistributedReceptionistClusteredTests.swift
- Tests/DistributedActorsTests/Cluster/Reception/_OpLogClusterReceptionistClusteredTests.swift
- Tests/DistributedActorsTests/Cluster/ShootTheOtherNodeClusteredTests.swift
- Tests/DistributedActorsTests/NodeDeathWatcherTests.swift
- Tests/DistributedActorsTests/TraversalTests.swift
Resolves https://github.com/apple/swift-distributed-actors/issues/949
> Make ClusterControl.membershipSnapshot async property

- Samples/Sources/SampleDiningPhilosophers/DistributedDiningPhilosophers.swift
- Sources/DistributedActors/Cluster/Cluster+Membership.swift
- Sources/DistributedActors/Cluster/ClusterControl.swift
- Sources/DistributedActors/Cluster/ClusterShell.swift
- Sources/DistributedActors/ClusterSystem.swift
- Sources/DistributedActorsTestKit/Cluster/ClusteredActorSystemsXCTestCase.swift
- Tests/DistributedActorsTests/Cluster/AssociationClusteredTests.swift
- Tests/DistributedActorsTests/Cluster/ClusterLeaderActionsClusteredTests.swift
- Tests/DistributedActorsTests/Cluster/MembershipGossipClusteredTests.swift
- Tests/DistributedActorsTests/MembershipTests.swift
Resolves https://github.com/apple/swift-distributed-actors/issues/948
~~Depends on https://github.com/apple/swift-distributed-actors/pull/969. Please look at https://github.com/apple/swift-distributed-actors/commit/8f46d0472dc92fa0f68289814d46785ea35d0af8 only.~~
> Add API to 'await joining cluster'

- Sources/DistributedActorsConcurrencyHelpers/lock.swift
Suprisingly this seems to have been building fine on CI, but triggeres errors in Xcode -- where I suppose the module checks are actually enforced...? I'll dig into the actual problems but we can fix this right away anyway.
> fix wrong cross module usage; seems this was not caught by CI / SwiftPM

- Samples/Package.swift
Update the swift tools version and required apple platforms
Would not build in Xcode on new macOS beta.
> update swift tools version and required apple platforms

- Sources/DistributedActors/Behaviors.swift
- Sources/DistributedActors/Cluster/DistributedNodeDeathWatcher.swift
- Sources/DistributedActors/ClusterSystem.swift
- Sources/DistributedActors/DistributedActorContext.swift
- Sources/DistributedActors/utils.swift
- Tests/DistributedActorsTests/Cluster/TestExtensions+MembershipDSL.swift
https://github.com/apple/swift-distributed-actors/issues/635 caused new warnings:
```
warning: parameter 'file' with default argument '#filePath' passed to parameter 'file', whose default argument is '#file'
```
This is because standard library's assertion and error functions use `#file`.
Also fix a few other trivial warnings.
> Fix #filePath related warnings

- Sources/DistributedActors/LifecycleMonitoring/LifecycleWatch.swift
- Sources/DistributedActors/LifecycleMonitoring/LifecycleWatchContainer.swift
- Sources/DistributedActorsTestKit/ActorTestKit.swift
- Sources/DistributedActorsTestKit/Task+Testing.swift
- Sources/DistributedActorsTestKit/TestProbes.swift
- Tests/DistributedActorsTests/DeadLetterTests.swift
- Tests/DistributedActorsTests/TraversalTests.swift
Resolves https://github.com/apple/swift-distributed-actors/issues/990
> Add ability to watch distributed actor with TestProbe

- Sources/DistributedActors/Cluster/Reception/OperationLogDistributedReceptionist.swift
I can't really easily reproduce the specific error that caused the logging, but as far as I can tell this is where it came from and I also didn't see this message anymore in my logs.
I was wondering if I should just drop it entirely or maybe still log it under the trace level for instance?
- Resolves #993
> Silence OpLogDistributedReceptionist.sendAckOps timeout logs

- Sources/DistributedActors/Cluster/Reception/OperationLogDistributedReceptionist.swift
Fix silenced error type for OpLogDistributedReceptionist.sendAckOps
The error type the was silenced by #996 was actually wrong, this fixes it.
> Use correct error type for timeout error silencing

- Tests/DistributedActorsTests/ActorAskTests.swift
**Motivation:**
`warning: 'wait()' is deprecated: Blocking API will be removed in favor of async await`
**Modifications:**
Switches `AskResponse.wait()` over to `await AskResponse.value`
**Result:**
- Resolves #994
> Remove all instances of AskResponse.wait() use

- Sources/DistributedActors/ClusterSystem.swift
Avoid the logging level settings from being overridden when replacing the "initialization logger" with a new one.
The logging settings were overridden at some point and it caused the settings to not be taken into account (see #1002)
Copy the logging level that had been set on the initial logger to apply it again to the logger that replaces it.
- Resolves #1002
> Fix logging level setting issue

- Sources/DistributedActors/ClusterSystemSettings.swift
- Sources/DistributedActorsTestKit/ShouldMatchers.swift
- Tests/DistributedActorsTests/Cluster/ClusterDiscoveryTests.swift
Resolves https://github.com/apple/swift-distributed-actors/issues/318
> Support seed nodes

- Tests/DistributedActorsTests/Cluster/ClusterLeaderActionsClusteredTests.swift
This is the single flaky test that keeps annoying us https://github.com/apple/swift-distributed-actors/issues/945
We need to revisit it
> Skip flaky test: ClusterLeaderActionsClusteredTests.test_singleLeader

- Sources/DistributedActors/ClusterSystemSettings.swift
This allows people to disable it; 
We'll want to remove the dependency in general though - and only enable it in tests for example.
> Make installSwiftBacktrace public before we remove it

- Sources/DistributedActors/ClusterSystem.swift
- Sources/DistributedActors/InvocationBehavior.swift
- Sources/DistributedActors/Serialization/Serialization+Invocation.swift
- Tests/DistributedActorsTests/ClusterSystemTests.swift
Resolves https://github.com/apple/swift-distributed-actors/issues/937
> Implement generic distributed actor method call

- Sources/DistributedActors/Clocks/VersionVector.swift
Part of https://github.com/apple/swift-distributed-actors/issues/999
> Hide VersionVector

- Sources/DistributedActors/Pattern/WorkerPool.swift
It was reported that beta-2 toolchain errors out on the missing `convenience` in this init. 
This is actually fixed by https://github.com/apple/swift-evolution/blob/main/proposals/0327-actor-initializers.md which @kavon implemented, so as soon as we get a stable Swift which does not need the convenience keyword we can drop it.
Adding for now to make life of early adopters easier.
> Avoid errors in old toolchains, add to-be-removed convenience keyword

- Sources/DistributedActors/Cluster/Cluster+Event.swift
- Sources/DistributedActors/Cluster/Cluster+Membership.swift
- Sources/DistributedActors/Cluster/ClusterShellState.swift
- Sources/DistributedActors/Cluster/DistributedNodeDeathWatcher.swift
- Sources/DistributedActors/Cluster/Downing/DowningSettings.swift
- Sources/DistributedActors/Cluster/Downing/TimeoutBasedDowningStrategy.swift
- Sources/DistributedActors/Cluster/Leadership.swift
- Sources/DistributedActors/Cluster/Reception/OperationLog.swift
- Sources/DistributedActors/Cluster/Reception/OperationLogDistributedReceptionist.swift
- Sources/DistributedActors/Cluster/Reception/_OperationLogClusterReceptionistBehavior.swift
- Sources/DistributedActors/Gossip/Gossiper+Shell.swift
- Sources/DistributedActors/Pattern/WorkerPool.swift
- Sources/DistributedActorsTestKit/ActorTestKit.swift
Part of https://github.com/apple/swift-distributed-actors/issues/999
> Make public enums into structs or hide them (part 1)

- Sources/DistributedActors/Pattern/WorkerPool.swift
Just a convenience change for people hitting the `Designated initializer for 'WorkerPool<Worker>' cannot delegate (with 'self.init'); did you mean this to be a convenience initializer?`  in old Xcode betas.
> Improve old betas compatibility

- docker/Dockerfile
Remove jazzy from build; it takes a long time to install ruby native extensions every time, adding up to build time -- and we're not using it anymore.
So long, and thanks for all the fish "Building native extensions. This could take a while..." 🐟 👋
> -jazzy remove jazzy; we're only using docc now

- Sources/DistributedActors/Cluster/Reception/OperationLogDistributedReceptionist.swift
- Sources/DistributedActors/ClusterSystem.swift
- Sources/DistributedActors/Receptionist/DistributedReceptionist.swift
- Tests/DistributedActorsTests/DistributedReceptionistTests.swift
- Tests/DistributedActorsTests/StubDistributedActorTests.swift
And therefore preventing their deinit/termination;
It is enough for the receptionist to store IDs, so let's have it do that.
This was not an issue with behaviors, since behavior actor lifecycle was
different and not refcount determined.
---
Resolves https://github.com/apple/swift-distributed-actors/issues/831
Depends on https://github.com/apple/swift-distributed-actors/pull/1049
**Actual change is the second commit**
> =reception prevent receptionist strong retaining actors

- Sources/DistributedActors/Cluster/SWIM/SWIMActor.swift
- Tests/DistributedActorsTests/Cluster/SWIM/SWIMActorClusteredTests.swift
Resolves https://github.com/apple/swift-distributed-actors/issues/1051
> Rewrite SWIMActor.sendPingRequests to use Swift concurrency

- Package.swift
- Tests/DistributedActorsTests/MetricsTestKit/MetricsTestKit.swift
- docker/docker-compose.2004.57.yaml
This adds support for Swift 5.7, but only to the legacy version.
Some projects are still using the legacy version but would like to use Swift 5.7. The dependencies of this project require updating for each Swift version.
* Updated dependencies for Swift 5.7.
* Worked around an issue in swift-metrics, but only did so for Swift 5.7 to keep backwards compatibility.
Swift 5.7 is now supported.
> Add Swift 5.7 support to legacy release/0.x branch.

- Sources/DistributedActors/Docs.docc/Clustering.md
- Sources/DistributedActors/Plugins/ClusterSingleton/ClusterSingleton.swift
Motivation:
Nice to get things perfect.
Modifications:
Minor typo corrections in docc.
Result:
Fewer docc typos.
> Correct typos in documentation

- Sources/DistributedActors/Docs.docc/Lifecycle.md
A typo in a documentation
changes the `watch(_ romeo: Romeo)` in Romeo actor
> Fix typo: Lifecycle example

- Sources/DistributedActors/Docs.docc/Clustering.md
Thanks @PeterAdams-A, fixed the link and added more examples for convenience API.
resolves https://github.com/apple/swift-distributed-actors/issues/1070
> =doc explain waiting for joined nodes better, fix link #1070

- Sources/DistributedCluster/TimeSpec.swift
- Tests/DistributedClusterTests/TimeSpecTests.swift
When Int is 32 bits, converting seconds to nanoseconds overflows. This change uses Int64 explicitly.
The change has been verified on a custom Linux armv7 system. Cross-compilation was used for the armv7 build, so I wasn't able to run the tests for that, but all tests pass on x86_64.
> Fix overflow in TimeSpec addition on 32-bit architectures

- Sources/DistributedCluster/Serialization/Serialization+Invocation.swift
Int arguments were serialized as Strings, but the deserializer expected bytes. I found these commented lines of code that seemed to be the correct way of serializing instead of using JSONEncoder, but I'm not sure if that is true. If it is, I guess the reason these were comments might still apply, but it does work in my simple application and all tests are successful.
> Use Serialization instead of JSONEncoder in recordArgument()

- .spi.yml
Setting up DocC doc on [Swift Package Index](https://blog.swiftpackageindex.com/posts/auto-generating-auto-hosting-and-auto-updating-docc-documentation/)
> DocC doc on Swift Package Index

- Sources/DistributedActorsTestKit/Task+Testing.swift
- Sources/DistributedActorsTestKit/TestProbes.swift
We were depending on a work in progress async-algorithms and Task.select was removed without replacement.
We only used this in testing though, so I reimplemented it as a task group based one.
It's not quite the same, but consensus is that such impl is "more correct"
resolves https://github.com/apple/swift-distributed-actors/issues/1108
> -testkit remove the Task.select based timeout impl, make a group based one

- Tests/DistributedClusterTests/Metrics/ActorMemoryTests.swift
Test fails on macos; Test should be adjusted to reflect smaller shell size
Adjust shell instance size (down)
passing tests on macos
> actor shell slimmed down a bit, adjust test

- Package.swift
bump atomics version
Especially this fix would be useful to us: https://github.com/apple/swift-atomics/issues/66
> Use 1.1.0 swift-atomics

- Sources/DistributedCluster/Plugins/ClusterSystemSettings+Plugins.swift
- Tests/DistributedClusterTests/Plugins/PluginsSettingsTests.swift
Motivation:
`PluginsSettings` doesn't allow same plugin to be installed more than once, but there is no way to check if a plugin is installed to avoid duplicate installation calls.
Modification:
Add `inInstalled` to `PluginsSettings`.
> Add helper method to check if a plugin is installed

- Sources/DistributedActorsTestKit/ShouldMatchers.swift
- Sources/DistributedCluster/Cluster/ClusterControl.swift
- Tests/DistributedClusterTests/Cluster/AssociationClusteredTests.swift
bug: We wrongly waited on the `self.node` to become up but should wait for the other node in `joined(node:)`
improvement: We should initiate joining when not already trying to and someone asks `try await joined(node:)` since the equivalent `join()` makes it seem like joined would do this as well
> ClusterControl.joined should cause joining; fix waiting issues

- Sources/DistributedCluster/Backoff.swift
- Sources/DistributedCluster/Plugins/ClusterSingleton/ClusterSingleton.swift
- Sources/DistributedCluster/Plugins/ClusterSingleton/ClusterSingletonBoss.swift
- Sources/DistributedCluster/Plugins/ClusterSingleton/ClusterSingletonSettings.swift
- Tests/DistributedClusterTests/Plugins/ClusterSingleton/ClusterSingletonPluginClusteredTests.swift
Don't review yet;
Resolves https://github.com/apple/swift-distributed-actors/issues/1123 by hardedning how the redirecring is done. This is still not optimal but hit IRGen issue
> Distributed singleton should be more careful with handover

- Sources/DistributedCluster/ActorID.swift
- Sources/DistributedCluster/ActorMetadata.swift
- Sources/DistributedCluster/ActorShell+Children.swift
- Sources/DistributedCluster/Cluster/ClusterEventStream.swift
- Sources/DistributedCluster/Cluster/Reception/OperationLogDistributedReceptionist.swift
- Sources/DistributedCluster/Cluster/SWIM/ClusterMembership+Converters.swift
- Sources/DistributedCluster/Cluster/SWIM/SWIMActor.swift
- Sources/DistributedCluster/ClusterSystem.swift
- Sources/DistributedCluster/Props.swift
- Sources/DistributedCluster/Refs.swift
- Sources/DistributedCluster/_ActorShell.swift
- Sources/DistributedCluster/utils.swift
- Tests/DistributedClusterTests/ClusterSystemTests.swift
- Tests/DistributedClusterTests/Metrics/ActorMemoryTests.swift
- Tests/DistributedClusterTests/ParentChildActorTests.swift
- Tests/DistributedClusterTests/Plugins/ClusterSingleton/ClusterSingletonPluginTests.swift
- Tests/DistributedClusterTests/_ActorRefReceptionistTests.swift
We need to "consume" the sneaky way we sneak in the "use this ID" into `assignID`. Without this we'd assign the same ID if someone were to create a singleton DURING the init() of another singleton.
I need to work around a few aggressive assertions that are trying to prevent users doing bad stuff that we actually do want to do here, but this'll work ok.
We "consume" the "props for spawn" during assignID as it should be. This works because that's code generated as first thing in every distributed actor init.
resolves #1131
rdar://112434926
relates to rdar://112433423 which is about a language feature to enable control over this properly.
> Prevent distributed singletons created during other's init from duping IDs

- Sources/DistributedCluster/LifecycleMonitoring/LifecycleWatch.swift
- Sources/DistributedCluster/LifecycleMonitoring/LifecycleWatchContainer.swift
These methods may be invoked from outside the actor, so synchronize them properly as the rest of the container.
I need to review some more code for safety and we should get a tsan build going here, we missed this for quite a while huh.
rdar://112815057
> =lifecycle missing synchronization; those methods may be invoked from outside actor

- Sources/DistributedCluster/Scheduler.swift
Fix Scheduler implementation for ILP32 platforms such as watchOS on arm64_32
Fix a bug in the Scheduler where converting the UInt64 nanoseconds value from a `Duration` value to the `DispatchTimeInterval`'s `Int` associated value causes an uncaught overflow and crash on devices with 32-bit Int values.
Add `DispatchTime.init(nowDelayedBy:)`, which computes the deadline and avoids casting to `Int`
Replace adhoc computations of Scheduler deadline with designated `DispatchTime.init(nowDelayedBy:)`
Prevents crash on ILP32 platforms when time delay exceeds a value that fits within a 32-bit Int
> Fix Scheduler implementation for ILP32 platforms such as watchOS

- Sources/DistributedCluster/ClusterEndpoint.swift
- Tests/DistributedClusterTests/Cluster/LeadershipTests.swift
Currently there is a bug in lowest address ordering where it will sort nodes and choose lowest not by address, but by alphabetical order (or guess unicode order) of systemName node's variables.
Changed implementation of Comparable for ClusterEndpoint and tweaked tests a bit.
- Resolves #1141
> Lowest address ordering fix

- Sources/DistributedCluster/Cluster/Downing/DowningStrategy.swift
- Sources/DistributedCluster/Cluster/Reception/OperationLogDistributedReceptionist.swift
Calling `__secretlyKnownToBeLocal` somehow doesn't guarantee isolation and crashes sometimes (e.g. #1140). Not sure what exact issue though, but anyway it's better to call `whenLocal`.
Moved from calling `__secretlyKnownToBeLocal` to `whenLocal` where possible.
- Resolves #1140
> Remove __secretlyKnownToBeLocal, adopt whenLocal

- Sources/DistributedCluster/Plugins/ClusterSingleton/ClusterSingletonSettings.swift
Using ClusterSingleton's host function with latest strict concurrency will result in an error:
```
Sending 'self'-isolated value of type 'ClusterSingletonSettings' with later accesses to actor-isolated
context risks causing data races
```
As ClusterSingletonPlugin is an actor and settings cross isolation in host function—it's better, and think safe, to mark it as Sendable.
> Made ClusterSingletonSettings sendable

- Sources/DistributedCluster/Serialization/Serialization+PrimitiveSerializers.swift
The integer deserializer was assuming that the input raw memory was correctly aligned for the integer type to be deserialized. In the test that was true on some platforms, but not others.
This caused a crash in the unit test.
Use `loadUnaligned` instead of `load` when loading integers.
Fixes https://github.com/apple/swift-distributed-actors/issues/1179.
> Fixed a crash on Swift 6.0+ where Integer deserialization was assuming aligned memory

- .github/workflows/pull_request.yml
- Sources/DistributedCluster/Backoff.swift
- Sources/DistributedCluster/Cluster/Cluster+Membership.swift
- Sources/DistributedCluster/Docs.docc/ClusterSingleton.md
- Sources/DistributedCluster/Docs.docc/Clustering.md
- Sources/DistributedCluster/Docs.docc/Contributing.md
- Sources/DistributedCluster/Docs.docc/Introduction.md
- Sources/DistributedCluster/Docs.docc/LeadershipSelectionSettings.md
- Sources/DistributedCluster/Docs.docc/Lifecycle.md
- Sources/DistributedCluster/Docs.docc/Observability.md
- Sources/DistributedCluster/Docs.docc/Receptionist.md
- Sources/DistributedCluster/Docs.docc/Security.md
- Sources/DistributedCluster/LifecycleMonitoring/LifecycleWatch.swift
- Sources/DistributedCluster/Receptionist/DistributedReceptionist.swift
- Sources/DistributedCluster/Serialization/Serialization.swift
- Tests/DistributedClusterTests/Cluster/ClusterLeaderActionsClusteredTests.swift
- Tests/DistributedClusterTests/ClusterSystemTests.swift
- Tests/DistributedClusterTests/Metrics/SWIMActorPeerMetricsTests.swift
- Tests/DistributedClusterTests/Plugins/ClusterSingleton/ClusterSingletonPluginClusteredTests.swift
The docs check pipeline was pinned to 5.10, because the 6.0 and newer docc detected more issues in the docs, and pinning down was the short-term workaround.
- Stop pinning to 5.10, instead let it use 6.0 (and soon 6.1).
- Fix all the docs issues that 6.0 found.
- Gets the CI back to green when using 6.0 docc: https://github.com/apple/swift-distributed-actors/actions/runs/13986968195/job/39162333702?pr=1192
> Move the docs pipeline to Swift 6.0 toolchains

- README.md
- Samples/Package.swift
Currently, the sample project doesn't compile because `swift-cluster-membership` requires macos 14.0.
```console
error: the executable 'SampleDiningPhilosophers' requires macos 13.0, but depends on the product 'DistributedCluster' which requires macos 14.0; consider changing the executable 'SampleDiningPhilosophers' to require macos 14.0 or later, or the product 'DistributedCluster' to require macos 13.0 or earlier.
```
Update the `Package.swift` file in `/Samples` to require macos 14 and bump to Swift 5.9 to support running in distributed mode.
Updated README to include `swift` in the run commands.
`Samples` project now compiles and runs.
> Fix the Samples project so that it compiles and runs.

- Package.swift
- Plugins/MultiNodeTestPlugin/plugin.swift
The integration tests for Swift 6.0 and 6.1 are hanging. They are passing on Swift 5.10. This is because SwiftPM started taking a lock over the package and cannot be run concurrently on the same package.
This is causing hangs in the integration test because it calls the `multi-node` package plugin which is running the `MultiNodeTestKitRunner` using `swift run MultiNodeTestKitRunner`.
This isn't the supported way for Swift package plugins to use executables from the package, which should instead be looked up from the context passed into the plugin.
Use the package plugin context to find the executable dependency used by the multi-node plugin.
Integration tests no longer hang on Swift 6.0 and 6.1.
> Fix hang using multi-node package plugin on Swift 6+

- Tests/DistributedClusterTests/Metrics/ActorMemoryTests.swift
There's an open PR to add macOS CI and one of the tests is failing because there's a hardcoded expected size of a class instance, which isn't using the correct value. It seems that, since this test was written, the class instance uses less memory. This is reproducible locally. Since this isn't a regression, we should just use the newer (better) value as the expected.
Update value used in test.
Tests now pass on macOS.
> Update expected memory size in actor memory tests

- Sources/DistributedCluster/ActorID.swift
- Sources/DistributedCluster/AsyncResult.swift
Parameter names were wrong, [fixes issue](https://github.com/apple/swift-distributed-actors/issues/1219).
> Documentation fix
